### ISSUE TITLE
create our GIT repo from a snapshot of univention 3.1 SVN repo

### ISSUE THREAD

**Issue by m-narayan** [m-narayan/smart#4]
We need to create a snapshot of univention 3.1 code base in our github repo for a stable development environment for our internal development.

**Comment by kartikm** [comment]
We can create clone of ucs and keep merging it until we reach at CD build stage. git-svn is bit tricky, hopefully, I'll be able to upload it by tonight.

**Comment by kartikm** [comment]
Done.
