### ISSUE TITLE
Build server Machine with Debian Stable netstat and no-ip client package

### ISSUE THREAD

**Issue by m-narayan** [m-narayan/smart#5]
Build the server with Debian stable netstat version and also install no-ip client package.

**Comment by m-narayan** [comment]
Debian Squeeze 6.0.6 does not install properly in the server machine and my guess is that there may be some hardware in the machine that is not supported by Squeeze 6.0.6.

I have installed Ubuntu 12.04 server with KVM virtualization and no-ip client in this machine. We can install Debian Squeeze 6.0.6 as the KVM guest for our development.

**Comment by kartikm** [comment]
Nice. Fine as of now. @gnumonk can you take forward and setup KVM guest for Debian 6.0.6 on it?

**Comment by m-narayan** [comment]
I have installed the SFTP in the machine and put Debian Squeeze iso in the path /var/www/ftp_dir

**Comment by gnumonk** [comment]
Can you provide me access ?

## 

dk

**Comment by m-narayan** [comment]
On 1/3/2013 10:46 AM, gnumonk wrote:

> Can you provide me access ?
> 
> ## 
> 
> dk
> 
> On Wed, Jan 2, 2013 at 7:58 PM, M Narayanan 
> notifications@github.comwrote:
> 
> > I have installed the SFTP in the machine and put Debian Squeeze iso 
> > in the
> > path /var/www/ftp_dir
> > 
> > —
> > Reply to this email directly or view it on 
> > GitHubhttps://github.com/m-narayan/smart/issues/5#issuecomment-11809655.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/m-narayan/smart/issues/5#issuecomment-11835259.

Check your email for access details. Can we also create 3 ids on that 
machine for us and add to the sudo group for admin tasks?

Thanks,
M Narayanan
