### ISSUE TITLE
Build server Machine with all required packages for development

### ISSUE THREAD

**Issue by m-narayan** [m-narayan/smart#6]
Once the server machine is up and able to ssh from the internet, We need to update the machine will all the required packages for development.

**Comment by kartikm** [comment]
Depends on #5

**Comment by kartikm** [comment]
This also involves some part of #10

**Comment by kartikm** [comment]
We're fine with,
1. Ubuntu machine
2. Debian machine

we have. So, this can be closed.

**Comment by m-narayan** [comment]
On Monday 07 January 2013 05:42 PM, Kartik Mistry wrote:

> We're fine with,
> 1. Ubuntu machine
> 2. Debian machine
> 
> we have. So, this can be closed.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/m-narayan/smart/issues/6#issuecomment-11949537.
> 
> Did we complete the Debian Repo mirror setup in that machines with all 
> the required packages for our development?
- M Narayanan

**Comment by kartikm** [comment]
1. Repo on machine is different issue #10 
2. What we needed are: debian-cd, git, svn and our src on server, which is done.
3. We can install any development package when needed.
