### ISSUE TITLE
Create private IRC for Smart development effort

### ISSUE THREAD

**Issue by m-narayan** [m-narayan/smart#7]

**Comment by kartikm** [comment]
Done. #arrivu is our channel. Try to join and let me know if you're able to. Also, let me know your, Deepak's IRC nicks so that I can whitelist invite.

**Comment by kartikm** [comment]
Oh, that's on Freenode server, btw. Caution: Even it is private, it is good idea to not disclose anything that's too 'private'!

**Comment by gnumonk** [comment]
My nick name is gnumonk.
